title: Neuroscience to Data Science
description: Long Form Jekyll theme

url: http://tyokogawa.github.com/tyokogawa.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

              

social:
   github: tyokogawa
   twitter: 
   facebook: 
   email: toheimtr@gmail.com

google_analytics: 
